import { StyleSheet} from 'react-native';


const styles = StyleSheet.create({
    container: {
        flex:1,
        backgroundColor: '#A5DEE4',
        alignItems: 'center',
        justifyContent: 'center',
        justifyContent: 'flex-start',
        },
    campos:{
            alignItems: 'center',
            justifyContent: 'flex-start',
        },
    text: {
            marginTop: 10,
            color: 'purple',
            fontSize: 18,
            textAlign: 'justify',
            fontWeight: 'bold'
          },
    caixaNome:{
        marginTop: 60,
        padding: 10,
        borderWidth: 2,
        borderColor: '#861B7F',
        height: 45,
        width: 320,
        backgroundColor:'#A5DEE4',
        fontSize: 14,
        fontWeight: 'bold',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute', 

            },
    caixaTelefone:{
        marginTop: 120,
        padding: 10,
        borderWidth: 2,
        borderColor: '#861B7F',
        height: 45,
        width: 320,
        backgroundColor:'#A5DEE4',
        fontSize: 14,
        fontWeight: 'bold',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute', 
            },
    caixaEndereco:{
        marginTop: 180,
        padding: 10,
        borderWidth: 2,
        borderColor: '#861B7F',
        height: 45,
        width: 320,
        backgroundColor:'#A5DEE4',
        fontSize: 14,
        fontWeight: 'bold',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute', 
    },
    caixaCidade:{
        marginTop: 240,
        padding: 10,
        borderWidth: 2,
        borderColor: '#861B7F',
        height: 45,
        width: 320,
        backgroundColor:'#A5DEE4',
        fontSize: 14,
        fontWeight: 'bold',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute', 
    },
    caixaEmail:{
            marginTop: 300,
            padding: 10,
            borderWidth: 2,
            borderColor: '#861B7F',
            height: 45,
            width: 320,
            backgroundColor:'#A5DEE4',
            fontSize: 14,
            fontWeight: 'bold',
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
            position: 'absolute', 
        },
        caixaSenha:{
            marginTop: 360,
            padding: 10,
            borderWidth: 2,
            borderColor: '#861B7F',
            height: 45,
            width: 320,
            backgroundColor:'#A5DEE4',
            fontSize: 14,
            fontWeight: 'bold',
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
            position: 'absolute', 
        },
        botao:{
            justifyContent: 'center',
            alignItems: 'center',
            position: 'absolute', 
            marginTop: 480
        },
        botaoTexto:{
        fontWeight: 'bold',
        color: '#861B7F',
        fontSize: 16,
            
        }
})

export default styles;